# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031e4cac7190881d538c5c94053d215748b2f0b0fce98a90880ea68ecffa97291b01ebfac4b7302df045e535f01f97fe7c296d00576b271401dc3396c2b34ea6

test:
  secret_key_base: 099fc7977d7dec4a0d79e90e67863ce2a3623524c36838224dbc97367c249e2f953eb1415c4ece8d40dd8fb2400a88f3fbd7c1bcfa62f53d884f9709f16d759d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
